"""
agents/report_writer.py
────────────────────────
Deterministic assembly of final report. No LLM call.
Pure Python string formatting — fastest possible node.
"""

from graph.state import AgentState
from datetime import datetime


def report_writer_node(state: AgentState) -> dict:
    research = state.get("research", {})
    market = state.get("market_intel", {})
    analysis = state.get("skill_analysis", {})
    gap = state.get("gap_strategy", {})
    draft = state.get("draft", {})
    critic = state.get("critic_feedback", {})

    match_pct = int(analysis.get("match_score", 0) * 100)
    quality_pct = int(critic.get("quality_score", 0) * 100)
    now = datetime.now().strftime("%B %d, %Y")
    apply_rec = "✅ APPLY NOW" if analysis.get("apply_now") else "⏳ PREP FIRST"
    loops = state.get("draft_loop_count", 1)

    # Per-dimension critic scores
    scores = critic.get("scores", {})
    score_table = "\n".join(
        f"| {dim.capitalize()} | {int(v*100)}% |"
        for dim, v in scores.items()
    ) if scores else "| N/A | — |"

    # Gap action plan table
    gap_plan = gap.get("gap_action_plan", [])
    gap_table = "\n".join(
        f"| {g['skill']} | {g['priority']} | {g['time_estimate_days']}d | {g['resource'][:60]} |"
        for g in gap_plan
    ) if gap_plan else "| No gaps identified | — | — | — |"

    # Market intel
    rare = market.get("rare_requirements", [])
    salary = market.get("market_salary_range", "N/A")
    market_insight = market.get("market_insight", "N/A")

    report = f"""# Job Application Report — {state.get("company_name", "N/A")}
**Generated:** {now} | **Skill Match:** {match_pct}% | **Draft Quality:** {quality_pct}% | **Drafts:** {loops}

---

## 🎯 Recommendation: {apply_rec}
{analysis.get("apply_reasoning", "")}

---

## 1. Company Research

**Overview**
{research.get("company_overview", "N/A")}

**Confirmed Tech Stack** *(from engineering blog + GitHub)*
{", ".join(research.get("tech_stack", [])) or "N/A"}

**Recent News**
{chr(10).join(f"- {n}" for n in research.get("recent_news", [])) or "- None found"}

**Company Health Signals**
{research.get("company_health", "N/A")}

**Contradictions Found Across Sources**
{chr(10).join(f"- ⚠️ {c}" for c in research.get("contradictions", [])) or "- None"}

**Culture Signals**
{chr(10).join(f"- {c}" for c in research.get("culture_signals", [])) or "- N/A"}

**Sources**
{chr(10).join(f"- {s}" for s in research.get("sources", [])) or "- N/A"}

---

## 2. Market Intelligence

**Salary Range:** {salary}
**Market Insight:** {market_insight}

**Skills common in similar roles (market baseline):**
{", ".join(market.get("common_stack", [])) or "N/A"}

**Rare requirements unique to this JD** *(mention these — shows you read carefully)*:
{", ".join(rare) or "None"}

---

## 3. Skill Gap Analysis

| Category | Skills |
|---|---|
| ✅ Matched | {", ".join(analysis.get("matched_skills", [])) or "None"} |
| ⚠️ Gaps | {", ".join(analysis.get("gap_skills", [])) or "None"} |
| 🔄 Transferable | {", ".join(analysis.get("transferable_skills", [])) or "None"} |

**Overall fit: {match_pct}%**

---

## 4. Gap Action Plan

| Skill | Priority | Time | Best Resource |
|---|---|---|---|
{gap_table}

**Quick wins** *(closeable in < 3 days — mention as "currently learning")*:
{", ".join(gap.get("quick_wins", [])) or "None"}

**Dealbreakers** *(likely to filter you out — be aware)*:
{", ".join(gap.get("dealbreakers", [])) or "None"}

---

## 5. Cover Letter

{draft.get("cover_letter", "Not generated")}

---

## 6. "Why This Company?" Answer

{draft.get("why_us_answer", "Not generated")}

---

## 7. Tailored Resume Bullets *(role-specific)*

{chr(10).join(f"- {b}" for b in draft.get("key_achievement_bullets", [])) or "None"}

---

## 8. ATS-Optimized Bullets *(keyword-matched to JD)*

{chr(10).join(f"- {b}" for b in draft.get("ats_resume_bullets", [])) or "None"}

---

## 9. LinkedIn DM *(to hiring manager / recruiter)*

{draft.get("linkedin_dm", "Not generated")}

---

## 10. Referral Ask Email

{draft.get("referral_ask", "Not generated")}

---

## 11. 1-Week Follow-Up Email

{draft.get("followup_email", "Not generated")}

---

## 12. Quality Assessment

| Dimension | Score |
|---|---|
{score_table}
| **Overall** | **{quality_pct}%** |

{"✅ Approved" if critic.get("approved") else "⚠️ Reached max iterations"} after {loops} draft(s)

**Issues flagged by critic:**
{chr(10).join(f"- {i}" for i in critic.get("issues", [])) or "- None"}

---
*Generated by Autonomous Job Application Research Agent*
"""
    return {"final_report": report, "last_completed_node": "report_writer"}
